services:
  auth-service:
    build:
      context: ./authService
      dockerfile: Dockerfile.prod
    ports:
      - "8081:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  card-service:
    build:
      context: ./cardService
      dockerfile: Dockerfile.prod
    ports:
      - "8082:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  game-service:
    build:
      context: ./gameService
      dockerfile: Dockerfile.prod
    ports:
      - "8083:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  user-service:
    build:
      context: ./userService
      dockerfile: Dockerfile.prod
    ports:
      - "8084:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  market-service:
    build:
      context: ./marketService
      dockerfile: Dockerfile.prod
    ports:
      - "8085:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  room-service:
    build:
      context: ./roomService
      dockerfile: Dockerfile.prod
    ports:
      - "8086:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "80:80"
    networks:
      - app-network
    depends_on:
      - auth-service
      - card-service
      - game-service
      - user-service
      - market-service
      - room-service
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/microservices.conf:/etc/nginx/conf.d/microservices.conf
      - ./frontend/dist:/usr/share/nginx/html

networks:
  app-network:
    driver: bridge

