services:
  auth-service:
    build:
      context: ./authService
      dockerfile: Dockerfile.dev
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./authService/src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - app-network


  card-service:
    build:
      context: ./cardService
      dockerfile: Dockerfile.dev
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./cardService/src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - app-network

  game-service:
    build:
      context: ./gameService
      dockerfile: Dockerfile.dev
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./gameService/src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - app-network

  user-service:
    build:
      context: ./userService
      dockerfile: Dockerfile.dev
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./userService/src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - app-network

  market-service:
    build:
      context: ./marketService
      dockerfile: Dockerfile.dev
    ports:
      - "8085:8085"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./marketService/src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - app-network

  room-service:
    build:
      context: ./roomService
      dockerfile: Dockerfile.dev
    ports:
      - "8086:8086"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    volumes:
      - ./roomService/src:/app/src
      - ~/.m2:/root/.m2
    networks:
      - app-network

  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "5173:5173"
      - "80:80"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - app-network
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  app-network:
    driver: bridge
